/**
 * Agent-facing assets (Agent Skills skill + commands): the target table
 * (where each runtime reads them), the installation plan and its application.
 *
 * This module knows NO real content: the catalog (the skill and the
 * commands, in Claude Code format) is given to it as a parameter
 * (`AgentAssetsOptions.catalog`) — which is what makes it testable on
 * fabricated fixtures before the generator
 * (`scripts/generate-agent-assets.mjs`, next task, see
 * `agent-assets.generated.ts`) even exists. In `@caesar/core` and not
 * `packages/cli`, same reason as `mcp-registration.ts` (see its header, and
 * `packages/cli/src/commands/mcp.ts:10-18`): the TUI's Integrations screen
 * will need it without depending on the CLI. The wiring into `caesar init` is
 * a later task — no dependency toward the CLI here.
 *
 * ## The target table — values verified empirically on 2026-08-12
 *
 * Confirmed on the actually installed binaries (effective listing, not the
 * documentation): `codex debug prompt-input` (codex 0.147.0), `opencode
 * debug skill` (opencode 1.18.16), `copilot skill list`, a bounded `claude`
 * invocation (claude 2.1.228), `strings` on the `agy` binary
 * (antigravity). Do NOT "fix" these paths without re-evaluating against the
 * real binary — several diverge from what one would naively guess:
 *
 * | Target                       | Skill (relative to the root)     | Commands (relative to the root)               |
 * |------------------------------|----------------------------------|-----------------------------------------------|
 * | shared (everything but claude)| `.agents/skills/caesar/`          | —                                              |
 * | `claude`                     | `.claude/skills/caesar/` (dedicated)| `.claude/commands/` (`caesar-*.md` files)      |
 * | `codex`                      | shared (`.agents/skills/caesar/`) | —                                              |
 * | `copilot`                    | shared                           | —                                              |
 * | `opencode`                   | shared                           | `.opencode/commands/` (`caesar-*.md`, plural)  |
 * | `antigravity`                | shared                           | —                                              |
 *
 * Why `claude` receives a DEDICATED copy rather than the shared one: claude
 * 2.1.228 does NOT read `.agents/skills/` — a skill placed only there would
 * remain invisible to it. Why `codex` must NOT receive, in addition, a
 * copy under `.codex/skills/caesar/`: codex 0.147.0 already reads `.agents/skills/`
 * at project level, and does NOT deduplicate by name — the same skill present
 * at both paths would appear twice in its listing. Same for `copilot`:
 * `.github/skills/caesar/` must not be shipped, `copilot skill list`
 * confirms the shared one suffices. Global scope: same paths, composed
 * from `homeDirectory()` rather than from the project root.
 *
 * Structural rule that follows, enforced by construction in
 * `ASSET_TARGETS` (a single `skillDir` field per target, never two): per
 * target, dedicated copy OR shared, never both; the shared one is produced
 * only once even when several targets designate it — deduplication
 * by identical resolved path, see `computePlan`.
 *
 * ## Files managed by caesar
 *
 * Namespace: the skill lives in a `caesar/` folder (already included in the
 * paths above), the commands are files prefixed `caesar-`. Everything
 * living under this namespace, at the table's locations, is deemed
 * generated by caesar — hence rewritten without ceremony when it differs
 * from the catalog (`update`, including a pre-existing `caesar/` or
 * `caesar-*.md` a user would have created themselves: the "managed by
 * caesar" contract applies from the location alone). A file already
 * identical to the catalog is NOT rewritten (`unchanged`, comparison
 * after CRLF→LF normalization, writing always in LF): the runtimes watch
 * these directories, an identical rewrite would trigger a reload for
 * nothing. An artifact present on disk at a managed location but absent
 * from the catalog is named in `stale` — never deleted, deletion
 * remaining an explicit gesture of the user or of a future dedicated
 * command.
 */
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { basename, isAbsolute, join, relative } from "node:path";
import { homeDirectory } from "./config.js";
import { writeFileAtomic } from "./fs-atomic.js";
import type { McpClient } from "./mcp-registration.js";

export type AgentAssetKind = "skill" | "command";

/** A source file of the catalog. `path` is relative to the artifact (e.g. "SKILL.md", "references/cli.md"), always in POSIX separators. */
export interface AgentAsset {
  kind: AgentAssetKind;
  id: string;
  path: string;
  content: string;
}

export type AssetScope = "project" | "global";

// ---------------------------------------------------------------------------
// Command rendering — one function per target format
// ---------------------------------------------------------------------------

function toLf(content: string): string {
  return content.replace(/\r\n/g, "\n");
}

/** Claude Code is the source format of the commands: identity rendering (normalized to LF, cf. the header). */
export function renderClaudeCommand(asset: AgentAsset): string {
  return toLf(asset.content);
}

const FRONTMATTER_PATTERN = /^---\n([\s\S]*?)\n---\n?/;

/** Fields that OpenCode's commands documentation recognizes (confirmed on 1.18.16) — everything else in the Claude Code frontmatter (`allowed-tools`, `argument-hint`, …) is foreign to it and must be removed. */
const OPENCODE_FRONTMATTER_KEYS = new Set(["description", "agent", "model"]);

/**
 * Adapts a source command (Claude Code frontmatter) to the OpenCode format:
 * keeps `description` (and `agent`/`model` if present), removes the rest of
 * the frontmatter, leaves the body intact.
 *
 * Line-by-line filtering rather than a real YAML parser: the three fields of
 * the source format (`description`, `allowed-tools`, `argument-hint`, see
 * `agent-assets.generated.ts`) are each a scalar on a single line,
 * and this filtering suffices without making `@caesar/core` depend on a YAML
 * library for that alone.
 */
export function renderOpencodeCommand(asset: AgentAsset): string {
  const content = toLf(asset.content);
  const match = FRONTMATTER_PATTERN.exec(content);
  if (!match) return content; // no frontmatter: nothing to adapt

  const full = match[0]!;
  const block = match[1] ?? "";
  const body = content.slice(full.length);
  const kept = block.split("\n").filter((line) => {
    const key = /^([A-Za-z0-9_-]+):/.exec(line)?.[1];
    return key === undefined || OPENCODE_FRONTMATTER_KEYS.has(key);
  });
  return `---\n${kept.join("\n")}\n---\n${body}`;
}

// ---------------------------------------------------------------------------
// The target table
// ---------------------------------------------------------------------------

/** A client of `MCP_CLIENTS`, as it reads caesar's skill and commands. See the fact table in the header. */
export interface AssetTarget {
  client: McpClient;
  /** Directory (relative to the root, or to HOME in global scope) where this client reads the "caesar" skill — dedicated or shared depending on the target, never both. */
  skillDir: string;
  /** Directory of this client's commands (`caesar-*.md` files); absent if this target reads no commands. */
  commandsDir?: string;
  /** Rendering applied to the source content (Claude Code format) to produce each command of this target. Ignored if `commandsDir` is absent. */
  renderCommand?: (asset: AgentAsset) => string;
}

/** Shared location: identical in value for every target without a dedicated copy, which is enough to make it a single production (deduplication by resolved path, `computePlan`). */
const SHARED_SKILL_DIR = ".agents/skills/caesar";

/** The only place where per-runtime path knowledge lives. */
export const ASSET_TARGETS: readonly AssetTarget[] = [
  {
    client: "claude",
    // Dedicated — required: claude 2.1.228 does not read .agents/skills/ (see the header).
    skillDir: ".claude/skills/caesar",
    commandsDir: ".claude/commands",
    renderCommand: renderClaudeCommand,
  },
  // codex reads .agents/skills/ at project level and does not deduplicate by name:
  // no additional copy under .codex/skills/caesar/ (see the header).
  { client: "codex", skillDir: SHARED_SKILL_DIR },
  // copilot skill list confirms the shared one suffices: no .github/skills/caesar/.
  { client: "copilot", skillDir: SHARED_SKILL_DIR },
  { client: "opencode", skillDir: SHARED_SKILL_DIR, commandsDir: ".opencode/commands", renderCommand: renderOpencodeCommand },
  { client: "antigravity", skillDir: SHARED_SKILL_DIR },
];

function targetFor(client: McpClient): AssetTarget {
  const target = ASSET_TARGETS.find((t) => t.client === client);
  if (!target) throw new Error(`Unknown target in the agent-assets table: "${client}".`);
  return target;
}

// ---------------------------------------------------------------------------
// Result
// ---------------------------------------------------------------------------

export type AgentAssetAction = "create" | "update" | "unchanged";

export interface AgentAssetFile {
  kind: AgentAssetKind;
  id: string;
  /** Absolute path on disk. */
  path: string;
  action: AgentAssetAction;
}

/** A `caesar`/`caesar-*` artifact present on disk at a managed location but absent from the catalog — named, never deleted. */
export interface AgentAssetStale {
  kind: AgentAssetKind;
  id: string;
  path: string;
}

export type SettingsMergeAction = "create" | "update" | "unchanged" | "skip";

export interface AgentAssetSettingsMerge {
  /** Always `<root>/.claude/settings.json` — never placed in global scope. */
  path: string;
  action: SettingsMergeAction;
  /** Tools added to `permissions.allow` during this pass; empty if "unchanged" or "skip". */
  added: string[];
}

export interface AgentAssetInstall {
  files: AgentAssetFile[];
  stale: AgentAssetStale[];
  /** Present only in project scope when `claude` is among the selected targets — see `computeSettingsMerge`. */
  settings?: AgentAssetSettingsMerge;
  /** Non-blocking warnings (today: invalid JSON in settings.json). */
  warnings: string[];
}

export interface AgentAssetsOptions {
  root: string;
  scope: AssetScope;
  /** The selected targets, by id from `MCP_CLIENTS`. */
  clients: readonly McpClient[];
  /** The asset catalog — generated (`AGENT_ASSETS`, `agent-assets.generated.ts`) or fabricated for a test. */
  catalog: readonly AgentAsset[];
}

// ---------------------------------------------------------------------------
// Path validation — before any `join`
// ---------------------------------------------------------------------------

/**
 * Rejects an asset path that would escape its artifact: absolute,
 * backslash, `..` segment, or empty segment.
 *
 * The `AgentAsset.path` contract promises POSIX separators only
 * (see its doc) — a backslash is therefore never a legitimate filename
 * character there. Rejected explicitly rather than split as a
 * separator or ignored as an opaque character: a split on `/`
 * alone let `"..\\..\\..\\..\\evil.md"` through (no `/`, hence treated
 * as a single segment without `..`), which does indeed escape the
 * root once recombined by `path.join` on Windows — defect found in
 * review of this task, see `agent-assets.test.ts`.
 */
function assertSafeAssetPath(path: string): void {
  if (path.startsWith("/")) {
    throw new Error(`Invalid asset path: "${path}" is absolute (expected relative to the artifact).`);
  }
  if (path.includes("\\")) {
    throw new Error(`Invalid asset path: "${path}" contains a backslash — only POSIX separators ("/") are accepted.`);
  }
  for (const segment of path.split("/")) {
    if (segment === "") throw new Error(`Invalid asset path: "${path}" contains an empty segment.`);
    if (segment === "..") throw new Error(`Invalid asset path: "${path}" contains ".." — an asset cannot escape its artifact.`);
  }
}

/**
 * Defense in depth: `skillDir`/`commandsDir` are constants of the
 * table, and `asset.path` is already validated (`assertSafeAssetPath`) —
 * this destination mathematically cannot escape `base`, but a clear
 * error beats a silent write elsewhere should the invariant break
 * one day.
 *
 * Separator-agnostic (split on `/[\\/]/`, never on a hardcoded `"../"`):
 * on Windows, `path.relative` renders its results with
 * backslashes, and a check coded on the POSIX separator alone let
 * this very defense pass inoperative — found in the same review as the
 * defect above.
 */
function assertWithinBase(path: string, base: string): void {
  const rel = relative(base, path);
  const segments = rel.split(/[\\/]/);
  if (isAbsolute(rel) || segments.includes("..")) {
    throw new Error(`Resolved path outside the targeted root: "${path}" (root: "${base}").`);
  }
}

function resolveBase(opts: AgentAssetsOptions): string {
  return opts.scope === "project" ? opts.root : homeDirectory();
}

// ---------------------------------------------------------------------------
// File-by-file diff
// ---------------------------------------------------------------------------

interface PlannedFile extends AgentAssetFile {
  content: string;
}

/** "create" if absent, "unchanged" if the disk (normalized CRLF→LF) already carries exactly `content`, "update" otherwise. One read, never a write — which is what makes `planAgentAssets` pure in this module's sense (writes nothing). */
function actionFor(path: string, content: string): AgentAssetAction {
  if (!existsSync(path)) return "create";
  const onDisk = toLf(readFileSync(path, "utf8"));
  return onDisk === content ? "unchanged" : "update";
}

function buildFileRecord(kind: AgentAssetKind, id: string, path: string, content: string): PlannedFile {
  return { kind, id, path, action: actionFor(path, content), content };
}

/** Orphans under a managed skill directory: any file present that is not in the current catalog. */
function scanStaleSkill(skillDir: string, plannedRelPaths: ReadonlySet<string>): AgentAssetStale[] {
  if (!existsSync(skillDir)) return [];
  const id = basename(skillDir);
  const stale: AgentAssetStale[] = [];
  const walk = (current: string, relPrefix: string): void => {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const rel = relPrefix ? `${relPrefix}/${entry.name}` : entry.name;
      const abs = join(current, entry.name);
      if (entry.isDirectory()) walk(abs, rel);
      else if (!plannedRelPaths.has(rel)) stale.push({ kind: "skill", id, path: abs });
    }
  };
  walk(skillDir, "");
  return stale;
}

const COMMAND_PREFIX = "caesar-";

/** Orphans under a managed commands directory: any `caesar-*.md` file no longer in the catalog. Commands of other origins (without the prefix) are neither scanned nor reported. */
function scanStaleCommands(commandsDir: string, plannedNames: ReadonlySet<string>): AgentAssetStale[] {
  if (!existsSync(commandsDir)) return [];
  const stale: AgentAssetStale[] = [];
  for (const entry of readdirSync(commandsDir, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.startsWith(COMMAND_PREFIX) || !entry.name.endsWith(".md")) continue;
    if (plannedNames.has(entry.name)) continue;
    stale.push({ kind: "command", id: entry.name.slice(COMMAND_PREFIX.length, -".md".length), path: join(commandsDir, entry.name) });
  }
  return stale;
}

// ---------------------------------------------------------------------------
// Merge of <root>/.claude/settings.json
// ---------------------------------------------------------------------------

/** The six MCP tools that modify none of the user's files — the only candidates for an automatic addition to `permissions.allow` (read-only: list agents/roles, status, await, logs, diff). */
const SETTINGS_MANAGED_TOOLS: readonly string[] = [
  "mcp__caesar__caesar_list_agents",
  "mcp__caesar__caesar_list_roles",
  "mcp__caesar__caesar_status",
  "mcp__caesar__caesar_await",
  "mcp__caesar__caesar_logs",
  "mcp__caesar__caesar_diff",
];

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

interface PlannedSettings extends AgentAssetSettingsMerge {
  /** Present only when `action` is "create" or "update" — it is what `installAgentAssets` writes. */
  content?: string;
}

/**
 * `permissions.allow` receives `SETTINGS_MANAGED_TOOLS`, append-if-absent:
 * deduplication by membership (never a duplicate of an already-granted
 * tool), everything else in the file preserved (unknown keys included,
 * including the other entries of `permissions`), never a removal of an
 * existing entry. `applyPlan` (`mcp-registration.ts`) is not reusable here:
 * it replaces an object it solely owns (`mcpServers.caesar`),
 * whereas `permissions.allow` belongs to the user and must only be
 * augmented.
 *
 * Invalid JSON, non-object root, or abnormal shape of `permissions`/
 * `permissions.allow` (present but not an object / not a list — `null`
 * included) ⇒ `action: "skip"` and a warning, never a write. This
 * last case is deliberately treated like invalid JSON rather than
 * silently falling back to `{}`/`[]`: a `"permissions": null` or
 * `"allow": "everything"` placed by hand by the user is a value they
 * chose, not an absence — overwriting it without saying so would have lost
 * that intention without any signal appearing in `warnings` (defect found
 * in review of this task, see `agent-assets.test.ts`). Acts only in
 * project scope, and only if `claude` is among the selected targets;
 * `~/.claude/settings.json` is never touched (global scope out of
 * scope for this file).
 */
function computeSettingsMerge(
  opts: AgentAssetsOptions,
  clients: readonly McpClient[],
): { settings?: PlannedSettings; warning?: string } {
  if (opts.scope !== "project" || !clients.includes("claude")) return {};

  const path = join(opts.root, ".claude", "settings.json");
  if (!existsSync(path)) {
    const allow = [...SETTINGS_MANAGED_TOOLS];
    const content = JSON.stringify({ permissions: { allow } }, null, 2) + "\n";
    return { settings: { path, action: "create", added: allow, content } };
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(path, "utf8"));
  } catch (error) {
    return {
      settings: { path, action: "skip", added: [] },
      warning: `Invalid JSON in ${path} (${error instanceof Error ? error.message : String(error)}) — permissions.allow not modified.`,
    };
  }
  if (!isRecord(parsed)) {
    return {
      settings: { path, action: "skip", added: [] },
      warning: `${path} does not contain a JSON object — permissions.allow not modified.`,
    };
  }

  const permissionsValue = parsed["permissions"];
  if (permissionsValue !== undefined && !isRecord(permissionsValue)) {
    return {
      settings: { path, action: "skip", added: [] },
      warning: `${path}: "permissions" is not an object (${JSON.stringify(permissionsValue)}) — permissions.allow not modified.`,
    };
  }
  const permissions = permissionsValue ?? {};

  const allowValue = permissions["allow"];
  if (allowValue !== undefined && !Array.isArray(allowValue)) {
    return {
      settings: { path, action: "skip", added: [] },
      warning: `${path}: "permissions.allow" is not a list (${JSON.stringify(allowValue)}) — permissions.allow not modified.`,
    };
  }
  const allow: unknown[] = allowValue ?? [];

  const missing = SETTINGS_MANAGED_TOOLS.filter((tool) => !allow.includes(tool));

  if (missing.length === 0) {
    return { settings: { path, action: "unchanged", added: [] } };
  }

  const merged = { ...parsed, permissions: { ...permissions, allow: [...allow, ...missing] } };
  const content = JSON.stringify(merged, null, 2) + "\n";
  return { settings: { path, action: "update", added: missing, content } };
}

// ---------------------------------------------------------------------------
// Plan and installation
// ---------------------------------------------------------------------------

interface Plan {
  files: PlannedFile[];
  stale: AgentAssetStale[];
  settings?: PlannedSettings;
  warnings: string[];
}

/**
 * Computes the full plan — reads only (destination files, managed
 * directories, `settings.json`), never a write. Shared by `planAgentAssets`
 * (which returns `computePlan` as-is, minus `content`) and
 * `installAgentAssets` (which uses it to know what to write): a single
 * diff logic, never two to keep synchronized.
 */
function computePlan(opts: AgentAssetsOptions): Plan {
  for (const asset of opts.catalog) assertSafeAssetPath(asset.path);

  const clients = [...new Set(opts.clients)];
  const targets = clients.map(targetFor);
  const base = resolveBase(opts);

  const skillAssets = opts.catalog.filter((asset) => asset.kind === "skill");
  const commandAssets = opts.catalog.filter((asset) => asset.kind === "command");

  const files: PlannedFile[] = [];
  const stale: AgentAssetStale[] = [];

  // The shared one is produced only once: several targets resolve to the
  // same path (SHARED_SKILL_DIR), and a Set merges them naturally.
  const skillDirs = new Set(targets.map((target) => join(base, target.skillDir)));
  const plannedSkillRelPaths = new Set(skillAssets.map((asset) => asset.path));
  for (const dir of skillDirs) {
    for (const asset of skillAssets) {
      const dest = join(dir, asset.path);
      assertWithinBase(dest, base);
      files.push(buildFileRecord(asset.kind, asset.id, dest, toLf(asset.content)));
    }
    stale.push(...scanStaleSkill(dir, plannedSkillRelPaths));
  }

  // The commands, conversely, are never shared: each target that reads
  // some has its own directory and its own rendering.
  const plannedCommandNames = new Set(commandAssets.map((asset) => `${COMMAND_PREFIX}${asset.path}`));
  for (const target of targets) {
    if (!target.commandsDir || !target.renderCommand) continue;
    const dir = join(base, target.commandsDir);
    for (const asset of commandAssets) {
      const dest = join(dir, `${COMMAND_PREFIX}${asset.path}`);
      assertWithinBase(dest, base);
      files.push(buildFileRecord(asset.kind, asset.id, dest, target.renderCommand(asset)));
    }
    stale.push(...scanStaleCommands(dir, plannedCommandNames));
  }

  const { settings, warning } = computeSettingsMerge(opts, clients);

  return { files, stale, settings, warnings: warning ? [warning] : [] };
}

function toPublicResult(plan: Plan): AgentAssetInstall {
  const result: AgentAssetInstall = {
    files: plan.files.map(({ content: _content, ...rest }) => rest),
    stale: plan.stale,
    warnings: plan.warnings,
  };
  if (plan.settings) {
    const { content: _content, ...rest } = plan.settings;
    result.settings = rest;
  }
  return result;
}

/** Pure: builds the plan without ever writing to disk (see `computePlan`, `actionFor`). */
export function planAgentAssets(opts: AgentAssetsOptions): AgentAssetInstall {
  return toPublicResult(computePlan(opts));
}

/**
 * Applies the plan: `writeFileAtomic` (`fs-atomic.ts`) for each file
 * whose action is not "unchanged", then `settings.json` if `action` is
 * "create" or "update". The result returned is that of the plan which
 * served to write — the actions it describes are already exactly what has
 * just been done, no need to reread the disk afterwards.
 */
export async function installAgentAssets(opts: AgentAssetsOptions): Promise<AgentAssetInstall> {
  const plan = computePlan(opts);

  for (const file of plan.files) {
    if (file.action === "unchanged") continue;
    await writeFileAtomic(file.path, file.content);
  }
  if (plan.settings?.content !== undefined) {
    await writeFileAtomic(plan.settings.path, plan.settings.content);
  }

  return toPublicResult(plan);
}
